### ISSUE TITLE
Numbro cannot find language files for a node app launched with 'forever'

### ISSUE THREAD

**Issue by gabooh** [foretagsplatsen/numbro#118]
I'm using forever (https://github.com/foreverjs/forever) to launch a nodejs application.
When launched with forever I get this message when settting the culture : "Error: Unknown culture : fr-FR"

It's because the process.title value is not 'node', but this : '/home/user/.nvm/versions/node/v4.1.2/bin/node'

So the function inNodejsRuntime() returns false. And the languages are thus not loaded.

I guess there is a more reliable method to detect a nodejs environement ? The process.title === 'node' is not correct in this particular case. Checking process.versions sounds like a better idea.

https://nodejs.org/api/process.html#process_process_versions

**Comment by BenjaminVanRyseghem** [comment]
Are you sure it's a better test?

In there, it looks like every other PR we rollback something :confused:

**Comment by gabooh** [comment]
Well, I'm not sure in the sense that I've not researched it that much, but the node version string is explicitly there to set the node version. If it's not empty, we are explicitly in a node environment. In my case I was in a node environment, but apparently they are cases when the title is changed.

The documentation for process.title : 
> Getter/setter to set what is displayed in 'ps'.

I'm sure that it works better for me, and honestly think it is more robust, but it's possible I'm not aware of other edge cases.

At least if anyone has the same problem this PR could prevent him from losing a few hairs :D

**Comment by stewart42** [comment]
I have had a similar issue, in our production environment we run node with fully qualified path ie `/blah/blah/bin/node` the `process.title` then is set to the fully qualified path. Could we not add something like this `(/node/i).test(process.title)` in the mean time?

**Comment by BenjaminVanRyseghem** [comment]
One exists to load languages. But I think it is only relevant in the node context so far

**Comment by stewart42** [comment]
Yeah I saw the `loadCulturesInNode()` function, it calls  `inNodejsRuntime` function which has the `process.title === 'node'` check which only works if you run `node` relying on your `$PATH` environment variable.

My suggestion is that we take the  `inNodejsRuntime` check out of it and / or create a wrapper around it with the check? This will allow us to call the  `loadCulturesInNode()` explicitly from our code executed in node.

**Comment by stewart42** [comment]
To reproduce the issue:

the command line 
```
which node
```
run node using the full path on OS X it is probably `/usr/local/bin/node`

in node 
```
$ /usr/local/bin/node
> var numbro = require('numbro');
undefined
> numbro.culture('en-ZA');
Error: Unknown culture : en-ZA
    at Function.numbro.culture (/blah/node_modules/numbro/numbro.js:778:23)
    at repl:1:8
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
> process.title
'/usr/local/bin/node'
```

**Comment by jamiter** [comment]
Also running in faulty node checks. In Meteor you can also have a fully qualified path to run node, but still not have access to `require`. So for me/Meteor that at least needs to be added. I will make a PR for it.

**Comment by BenjaminVanRyseghem** [comment]
:+1:

**Comment by jamiter** [comment]
PR added here: https://github.com/foretagsplatsen/numbro/pull/131

**Comment by BenjaminVanRyseghem** [comment]
should we close this issue as #131 has been merged?

**Comment by stewart42** [comment]
The  title checking for node is problematic. It fails if you use gulp or if as per #133 or the example above.

@BenjaminVanRyseghem would be okay to move the `inNodejsRuntime()` check outside of the method which then would allow us to explicitly call `loadCulturesInNode` from our code? 

`inNodejsRuntime()`  could still be used to (safetly) attempt auto load on first time call of the module in node

**Comment by BenjaminVanRyseghem** [comment]
@stewart42 why not :smile:

**Comment by gabooh** [comment]
Sorry, time flies, the project using this was on hold.
So, using loadCulturesInNode() works, but I still think merging my proposed change makes sense : I think it's more robust using process.versions.node.

@BenjaminVanRyseghem feel free to merge or close this issue, I have a clean and working solution anyway :)

Thank you @stewart42 for the fix.
