### ISSUE TITLE
Breaking change

### ISSUE THREAD

**Issue by arnaudbenard** [foretagsplatsen/numbro#141]
Your new release broke on our side. Indeed we get the following error:

```
Error: Cannot find module './cs-CZ.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/ubuntu/website/node_modules/numbro/dist/languages.js:856:20)
```

It looks like your code does not require the right path:
https://github.com/foretagsplatsen/numbro/blob/develop/dist/languages.js#L856

**Comment by BenjaminVanRyseghem** [comment]
indeed. I figured it out yesterday.

Unfortunately, the author of the code did not answered yet :smile:

**Comment by arnaudbenard** [comment]
@BenjaminVanRyseghem No problem :+1: We used the previous version :dancer:

**Comment by mmollick** [comment]
Just submitted a new PR to fix this. Sorry about that guys!
